name:  Build My Application

on: [push]

jobs:
  build:
    name: Build Our App
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2  
      - name: Print Current Directory
        run: pwd
      - name: List Files in Directory
        run: ls
      - name: Use DotNet Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Check Dotnet CLi
        run: dotnet build
      - name: List Files in Directory
        run: ls .\TrickingLibirary.Api\ -R
      - name: Check NPM
        run: npm -v